config/routes.rb
Essaypros::Application.routes.draw do

  resources :customers
  resources :articles

  resources :orders do
    resources :uploadfiles
    resources :messages
    collection do
      post 'notification'
    end
  end
  resources :sessions, :only=>[:new, :create, :destroy]
  match '/signup', :to=>"customers#new"
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy', :via=>:delete
  match '/order_now', :to=>"orders#new"
  match '/pricing', :to=>'pages#pricing'
  match '/order_now', :to=>"orders#new"
  resources :password_resets

  root :to => 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author, :body, :published_at, :title
  belongs_to :customer
  #default_scope :order=>'articles.created_at DESC'
  def self.latest
  	find :all, :limit => 10, :order => "articles.id desc"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  #before_filter :admin_user
  def index
   # @articles = Article.all
   @articles = Article.paginate :page=>params[:page], :order=>'created_at desc',
    :per_page =>5
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    #@article = Article.new(params[:article])
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def recent_posts
    #@articles = Article.all
    @articles = Article.latest
  end
end

app/views/articles/_article.html.erb
<li>
	<%=@articles.each do |article| %>
	<span class="content"> <%=article.body %> </span>
	<span class="timestamp">
		Posted <%=time_ago_in_words(article.created_at) %> ago
	</span>
	<% end %>
</li>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "articles", media: "all" %>
<div id="elixirs">
<% unless signed_in?%>
<div id="login">
  <%= render :file => 'sessions/new' %>
</div>
  <% end %>
  <p></p>
<div id="features">
  <h4><span class="btn btn-large btn btn-info">Custom Paper Writing Services</span></h4>
    <ul>
   <li>Essays</li>
    <li>Term Papers</li>
    <li>Research Papers </li>
    <li>Thesis Papers</li>
    <li>Dissertations</li>
    <li>Assignments</li>
    <li>Reviews</li>
    <li>Presentations</li>
    <li>Case Studies</li>
    <li>Courseworks</li>
    <li>Homeworks</li>
    <li>Creative Writing</li>
    <li>Critical Thinking</li>
    <li>Annotated Bibliography</li>
    <li>Proposal</li>
    <li>Research Report</li>
    <li>...and Others!</li>
</ul>
</div>
<p></p>
<div id="features">

<h4><span class="btn btn-large btn btn-info">Advantages</span></h4>
    <ul>
   <li>30 Days Money Back Guarantee</li>
    <li>Prices as low as 10$/page</li>
    <li>We accept urgent orders</li>
    <li>Experienced and capable writers</li>
    <li>Plagiarism detection systems/software</li>
    <li>No charges on revisions</li>
    <li>We respond to all types of assignments</li>
    <li>Flexible pricing and great discounts</li>
    <li>...and Others!</li>
</ul>
</div>
</div>
<div id="index">
<% @articles.each do |article| %>
<div id="blog">
    <h3><u><%= article.title %></u></h3>
    Published by <u><%= article.author %></u></br>
    <u><%= article.published_at %></u></br>
    <p></p>
    <%= truncate article.body, :length => 900 %></br>
    <span class="btn btn-large btn btn-default"><h4><%= link_to 'Read More', article %></h4></span>
    <p></p>
    <span class="btn btn-large btn btn-default"><h3><%=link_to "Buy Similar Paper", order_now_path %></h3></span></br>
    <% if signed_in? && current_user.admin %>
    <span class="btn btn-large btn btn-default"><%= link_to 'Edit', edit_article_path(article) %></span></br>
    <span class="btn btn-large btn btn-default"><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></span></br>
    <% end %>
    </div>
<% end %>
</div>
<% if signed_in? && current_user.admin %>
<span class="btn btn-large btn btn-default"><%= link_to 'New Article', new_article_path %></span>
<% end %>
</div>
<p></p>

app/views/articles/new.html.erb
<%= stylesheet_link_tag "articles", media: "all" %>

<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "articles", media: "all" %>
<div id="elixirs">
<% unless signed_in?%>
<div id="login">
  <%= render :file => 'sessions/new' %>
</div>
  <% end %>
  <p></p>

<div id="features">

<h4><span class="btn btn-large btn btn-info">Advantages</span></h4>
    <ul>
   <li>30 Days Money Back Guarantee</li>
    <li>Prices as low as 10$/page</li>
    <li>We accept urgent orders</li>
    <li>Experienced and capable writers</li>
    <li>Plagiarism detection systems/software</li>
    <li>No charges on revisions</li>
    <li>We respond to all types of assignments</li>
    <li>Flexible pricing and great discounts</li>
    <li>...and Others!</li>
</ul>
</div>
</div>
<div id="index">
  <div id="blog">
<p>
  <h3><u><%= @article.title %></u></h3>
    Published by <u><%= @article.author %></u></br>
    <u><%= @article.published_at %></u></br>
</p>
<p>
  <%= @article.body %>
</p>
<p>
<span class="btn btn-large btn btn-default"><%= link_to 'Back', articles_path %></span>
</p>
<div>
<span class="btn btn-large btn btn-default"><h2><%=link_to "Buy Custom Essay", order_now_path %></span></h2>
</div>
</div>
</div>