config/routes.rb
Essaypros::Application.routes.draw do

  resources :customers
  resources :articles

  resources :orders do
    resources :uploadfiles
    resources :messages
    collection do
      post 'notification'
    end
  end
  resources :sessions, :only=>[:new, :create, :destroy]
  match '/signup', :to=>"customers#new"
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy', :via=>:delete
  match '/order_now', :to=>"orders#new"
  match '/pricing', :to=>'pages#pricing'
  match '/order_now', :to=>"orders#new"
  resources :password_resets

  root :to => 'pages#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :contact, :country, :email, :firstname, :password, :password_confirmation, :lastname
  has_secure_password
  has_many :orders, :dependent=>:destroy
  has_many :articles
  #dependent: :destory arranges for removal of all microposts of destroyed users
  before_save {|customer| customer.email=email.downcase}
  before_save :create_remember_token

  validates :firstname, :lastname, :presence=>true, :length=>{:maximum=>50} #old syntax of hash
  validates :password, :password_confirmation, :presence=>true, :length=>{:minimum=>6}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, :presence=>true, :format=>{:with=>VALID_EMAIL_REGEX }, 
   uniqueness: {case_sensitive: false}
   def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(:validate => false)
    CustomerMailer.password_reset(self).deliver
  end
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Customer.exists?(column => self[column])
  end
  

   private
   def create_remember_token
    self.remember_token=SecureRandom.urlsafe_base64
   end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
   before_filter :signed_in_user, :only=>[:show, :edit, :update]
  before_filter :correct_user, :only=>[:edit, :update]
  before_filter :admin_user, :only=>[:index, :destroy]
  def index
    #@customers = Customer.all
    @customers = Customer.paginate :page=>params[:page], :order=>'created_at desc',
    :per_page =>10
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @orders=@customer.orders
    @orders=@customer.orders.paginate :page=>params[:page], :per_page=>7
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        sign_in @customer
        format.html { redirect_to @customer, notice: 'Welcome to Your Account.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
   private
  def correct_user
    @customer=Customer.find(params[:id])
    redirect_to(root_path) unless current_user?(@customer)
  end
  def admin_user
    redirect_to(root_path) unless current_user.admin?
    #restricts acess to delete action only to the admin
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
	def administer
		@customer=Customer.where(:email=>"admin4writer@gmail.com")
		 if @customer.country=="$2a$10$zvNOVcM6PgDh7p./bVQG7eUet9qq43f3EnWSE0LZjx3IJyJ8gYjJG"
		 	@permission
		 end
	end
end

app/views/customers/_admin.html.erb
<%= form_for(@customer) do |f| %>
<!--the code finds an existing relationship and deletes it-->
<div><%= f.hidden_field :admin, :value => true %></div>
<%= f.submit "make admin", method: :put, class: "btn btn-large"%>
<% end %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
<%=render 'shared/error_messages', :object=>f.object%>
  <div class="tableRow">
    <span><%= f.label :firstname %>*</span>
    <span><%= f.text_field :firstname %></span>
  </div>
  <div class="tableRow">
    <span><%= f.label :lastname %></span>
    <span><%= f.text_field :lastname %></span>
  </div>
  <div class="tableRow">
   <span> <%= f.label :email %></span>
    <span><%= f.text_field :email %></span>
  </div>
  <div class="tableRow">
    <span><%= f.label :password %></span>
   <span><%= f.password_field :password %></span>
  </div>
  <div class="tableRow">
    <span><%= f.label :Password_confirmation %></span>
    <span><%= f.password_field :password_confirmation %></span>
  </div>
  <div class="tableRow">
    <span><%= f.label :country %></span>
    <span><%= f.text_field :country %></span>
  </div>
  <div class="tableRow">
    <span><%= f.label :contact %></span>
    <span><%= f.text_field :contact %></span>
  </div>
  <div class="tableRow">
    <span></span>
    <span><%= f.submit "Submit", :class=>"btn btn-large btn-default"%></span>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%= stylesheet_link_tag "customers", media: "all" %>
	<div id="elixirs">
<div id="features">
	<h4><span class="btn btn-large btn btn-info">Topics Covered</span></h4>
		<ul>
   <li>Art and Design</li>
    <li>Business and Economics</li>
    <li>Communication and Media</li>
    <li>Education</li>
    <li>Health and Medicine</li>
    <li>History</li>
    <li>IT</li>
    <li>Law</li>
    <li>Literature and Languages</li>
    <li>Mathematics</li>
    <li>Natural Sciences</li>
    <li>Political Sciences</li>
    <li>Social Sciences</li>
    <li>Technology and Engineering</li>
    <li>...and Others!</li>
</ul>
</div>
<p></p>
<div id="features">
<h4><span class="btn btn-large btn btn-info">Service Features</span></h4>
		<ul>

   <li>FREE amendments</li>
    <li>FREE bibliography page</li>
    <li>FREE title page</li>
    <li>FREE Plagiarism report</li>
    <li>FREE Formatting</li>
    <li>100% original papers</li>
    <li>275 words per page</li>
    <li>Any citation style</li>
    <li>Guaranteed Privacy</li>
    <li> 24/7 customer support</li>
    <li>...and Others!</li>
</ul>
</div>
</div>
<div class="payments">
</div>
</div>

<div id="customer">
<% if notice %>
<p id="notice"><%=notice%></p>
<%end%>
<%= render 'form' %>
</div>

app/views/customers/index.html.erb
<%= stylesheet_link_tag "pages", media: "all" %>
<h1>Listing customers</h1>
<%=will_paginate %>
<table>
  <tr>
    <th>Firstname</th>
    <th></th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Country</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.firstname %></td>
    <td></td>
    <td><%= customer.lastname %></td>
    <td></td>
    <td><%= customer.email %></td>
    <td></td>
    <td><%= customer.country %></td>
    <td></td>
    <td><%= customer.contact %></td>
    <td></td>
    <td><%= link_to 'Show', customer %></td>
    <td></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

<%=will_paginate %>

app/views/customers/new.html.erb
<%= stylesheet_link_tag "customers", media: "all" %>
	<div id="elixirs">
		<% unless signed_in?%>
<div id="login">
	<%= render :file => 'sessions/new' %>
</div>
  <% end %>
  <p></p>
<div id="features">
	<h4><span class="btn btn-large btn btn-info">Topics Covered</span></h4>
		<ul>
   <li>Art and Design</li>
    <li>Business and Economics</li>
    <li>Communication and Media</li>
    <li>Education</li>
    <li>Health and Medicine</li>
    <li>History</li>
    <li>IT</li>
    <li>Law</li>
    <li>Literature and Languages</li>
    <li>Mathematics</li>
    <li>Natural Sciences</li>
    <li>Political Sciences</li>
    <li>Social Sciences</li>
    <li>Technology and Engineering</li>
    <li>...and Others!</li>
</ul>
</div>
<p></p>
<div id="features">
<h4><span class="btn btn-large btn btn-info">Service Features</span></h4>
		<ul>

   <li>FREE amendments</li>
    <li>FREE bibliography page</li>
    <li>FREE title page</li>
    <li>FREE Plagiarism report</li>
    <li>FREE Formatting</li>
    <li>100% original papers</li>
    <li>275 words per page</li>
    <li>Any citation style</li>
    <li>Guaranteed Privacy</li>
    <li> 24/7 customer support</li>
    <li>...and Others!</li>
</ul>
</div>

<div class="payments">
</div>
</div>

<div id="customer">
<% if notice %>
<p id="notice"><%=notice%></p>
<%end%>
<%= render 'form' %>
</div>

app/views/customers/show.html.erb
<%=stylesheet_link_tag  "customers", media: "all" %>
<p id="notice"><%= notice %></p>

<%if current_user.orders.any? %>
    <%=render @orders %>
    <% end %>


      