config/routes.rb
Essaypros::Application.routes.draw do

  resources :customers
  resources :articles

  resources :orders do
    resources :uploadfiles
    resources :messages
    collection do
      post 'notification'
    end
  end
  resources :sessions, :only=>[:new, :create, :destroy]
  match '/signup', :to=>"customers#new"
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy', :via=>:delete
  match '/order_now', :to=>"orders#new"
  match '/pricing', :to=>'pages#pricing'
  match '/order_now', :to=>"orders#new"
  resources :password_resets

  root :to => 'pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :citation, :documenttype, :instructions, :language, :level, :pages, :references, :subject, :topic, :deadline, :price, :spacing, :urgency, :marking, :purchased_at
  belongs_to :customer
  has_many :payments
  has_many :uploadfiles
  has_many :messages
  has_many :states
  validates :citation, :documenttype, :instructions, :language, :level, :pages, :references, :subject, :topic, :deadline, :spacing, :presence=>true
  default_scope :order=>'orders.created_at DESC'
Subject_Type = ["Art", "Architecture", "Dance", "Design Analysis", "Drama", "Movies", "Music", "Paintings", "Theatre", "Biology", 
                  "Business", "Chemistry", "Communications and Media", "Advertising", "Communication Strategies", "Journalism", 
                  "Public Relations", "Creative writing", "Economics", "Accounting", "Case Study", "Company Analysis", 
                  "E-Commerce", "Finance", "Investment", "Logistics", "Trade", "Education", "Application Essay",  
                  "Education Theories", "Engineering", "Ethics", "History", "Law", "Criminology", "Linguistics", "Literature", 
                  "Management", "Marketing", "Mathematics", "Healthcare", "Nursing", "Nutrition", "Pharmacology", "Sport", 
                  "Nature", "Agricultural Studies", "Anthropology", "Astronomy", "Environmental Issues", "Geography", 
                  "Geology", "Philosophy", "Physics", "Political Science", "Psychology", "Religion and Theology", "Sociology", 
                  "Technology", "Aviation", "Computer Science", "Web Design", "Tourism"]
  Document_Type=["Essay", "Term Paper", "Research Paper", "Coursework", "Book Report", "Book Review", "Movie Review", "Dissertation",
 "Thesis", "Thesis Proposal", "Research Proposal", "Formatting", "Admission Essay", "Scholarship Essay", 
 "Personal Statement", "Editing", "Proofreading", "Case Study", "Lab Report", "Math Problem", "Article", 
 "Article Critique", "Annotated Bibliography", "Reaction Paper", "PowerPoint Presentation", 
 "Statistics Project", "Multiple Choice Questions", "Other"]
 Academic_Level=["High School", "Undergraduate", "Master", "Ph.D."]
 Citation_Style=["APA", "MLA", "Turabian", "Chicago", "Harvard", "Oxford", "Vancouver", "CBE", "Other"]
 Preffered_Language=["English (U.S.)", "English (U.K.)"]
 #Urgency=["8 hours", "12 hours", "24 hours", "48 hours", "3 days", "5 days", "7 days", "10 days", "15 days", "25 days"]
 Spacing=["Single", "Double"]
 


 def paypal_url(return_url, notify_url)
  values={

    :business=>"ptztom-facilitator@gmail.com",
    :cmd=>"_cart", #had used a cart without underscore
    :upload=>1,
    :return => "http://calm-meadow-7091.herokuapp.com/orders",
    :invoice=>id,
    :notify_url=>notify_url
  }
  values.merge!({
    #amount is in cents
    "amount_1"=>price,
    "item_name_1"=>topic,
    "item_number_1"=>id,
    "quantity_1"=>1

    })
  #for test transactions we use the URL below
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  before_filter :signed_in_user, :only=>[ :index, :create, :new]
  
  def index
    #@orders = Order.all
    @orders = Order.paginate :page=>params[:page], :order=>'created_at desc',
    :per_page =>20
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

    @order=Order.find(params[:id])
    @uploadfile=@order.uploadfiles.new
    calculator @order
    @orders=current_user.orders.paginate(page: params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    #@order = Order.new(params[:order])
    @order=current_user.orders.build(params[:order])
    respond_to do |format|
      if @order.save
        calculator @order
        @order.update_attributes(:price=>@total_price)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  def notification
    if params[:item_number1] && !params[:item_number1].empty?
      #paypal sends an IPN even when the transaction is void
      if params[:payment_status]=="Completed"
        @order=Order.find(params[:item_number1].to_i) rescue nil
        @order.payments.build(:quantity=>1, :amount=>params[:mic_gross_1], :status=>params[:payment_status]).save unless @order.nil?
      end
    end
    render :nothing=>true
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def calculator(order)
		if order.level=="High School"
			if order.deadline==8
				price=28
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==12
				price=25
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==24
				price=22
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==48
				price=19
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==72
				price=16
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==120
				price=13
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==168
				price=10
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==240
				price=7
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==360
				price=7
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==600
				price=7
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
		end
		if order.level=="Undergraduate"
			if order.deadline==8
				price=35
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==12
				price=32
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==24
				price=29
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==48
				price=26
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==72
				price=23
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==120
				price=20
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==168
				price=17
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==240
				price=14
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==360
				price=14
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==600
				price=14
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
		end
		if order.level=="Master"
			if order.deadline==8
				price=42
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==12
				price=39
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==24
				price=36
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==48
				price=33
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==72
				price=30
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==120
				price=27
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==168
				price=24
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==240
				price=21
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==360
				price=21
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==600
				price=21
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
		end
		if order.level=="Ph.D."
			if order.deadline==8
				price=49
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==12
				price=46
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==24
				price=43
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.urgency==48
				price=40
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==72
				price=37
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==120
				price=34
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==168
				price=31
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==240
				price=28
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==360
				price=28
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
			if order.deadline==600
				price=28
				if order.spacing=="Single"
				@total_price=(order.pages)*price*2
				else
				@total_price=(order.pages)*price
			end
			end
		end
	end
end

app/views/orders/_follow.html.erb
<%= form_for(@order.markings.build(complete_id: @order.id)) do |f| %>
<div><%= f.hidden_field :complete_id %></div>
<div><%= f.hidden_field :status, :value => 'complete' %></div>
<%= f.submit "Complete", class: "btn btn-large btn-primary" %>
<% end %>

app/views/orders/_follow_form.html.erb
<div id="follow_form">
<% if @order.following?(@order) %>
<%= render 'unfollow' %>
<% else %>
<%= render 'follow' %>
<% end %>
</div>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="contact">
  <div class="tableRow">
 <span> <%= f.label "Topic"%></span>
  <span><%= f.text_field :topic, :placeholder=>"Creative Writing" %></span>
</div>
<div class="tableRow">
  <span><%= f.label "Subject Area"%></span>
  <span><%= f.select :subject, Order::Subject_Type,
                        :prompt=>"Select a Topic" %></span>
</div>
<div class="tableRow">
  <span><%= f.label "Type of Document"%></span>
  </span><%= f.select :documenttype, Order::Document_Type,
                        :prompt=>"Select type of Paper" %></span>
</div>
<div class="tableRow">
  <span><%= f.label "Number of Pages" %></span>
   <span> <%= f.number_field :pages, :min=>"1", :value=>"1", :max=>"200", :placeholder=>"1 page/Approx 275 Words" %>Pages</span>
 </div>
 <div class="tableRow">
  <span><%= f.label "Spacing" %></span>
   <span> <%= f.select :spacing, Order::Spacing, :prompt=>"Select Spacing"%></span>
 </div>
  <div class="tableRow">
  <span><%= f.label "Urgency" %></span>
  <span><%= f.select(:deadline, { "8 Hours" => "8",  "12 Hours" => "12",  "24 Hours" => "24",  "48 Hours" => "48", 
    "3 Days" => "72", "5 Days" => "120", "7 Days" => "168", "10 Days" => "240", "15 Days" => "360", "25 Days" => "600"}) %></span>
</div>
<div class="tableRow">
 <span><%= f.label "Number of References"%></span>
  <span><%= f.number_field :references, :min=>"0", :value=>"0"%></span>
  </div>
  <div class="tableRow">
 <span><%= f.label :citation %></span>
    <span><%= f.select :citation, Order::Citation_Style,
                       :prompt=>"Select Citation Style"%></span>
  </div>
  <div class="tableRow">
 <span><%= f.label :level %></span>
  <span><%= f.select :level, Order::Academic_Level, :prompt=>"Select Academic Level"%></span>
</div>
  <div class="tableRow">
 <span><%= f.label :language %></span>
    <span><%= f.select :language, Order::Preffered_Language, :prompt=>"Select Language of Preference" %></span>
  </div>
<div class="tableRow">
 <span><%= f.label :instructions %></span>
      <span><%= f.text_area :instructions, :cols => "40", :rows => "7", :placeholder=>"Type Order Instructions" %></span>
    </div>
  <div class="tableRow">
 <span><%= f.submit "Order Now", :class=>"btn btn-small btn-default"%></span>
</div>
<% end %>
</div>

app/views/orders/_order.html.erb
    <table class="table table-striped">

        <thead>

            <tr>

                <th>Project Description</th>

                <th>Order ID</th>

                <th>Time remaining</th>

                <th>Order Status</th>
                <th>Messages</th>

            </tr>

        </thead>

        <tbody>

            <tr>

                <td rowspan="3"><%= link_to "#{order.instructions}", order%></td>

                <td>#<%=order.id%></td>

                <td><%=order.urgency%></td>
                <td> <% if order.marking=="complete"%>
                    <span class="btn btn-small btn btn-default">Complete</span>
                    <% end %>
                    <% if order.marking=="revision" %>
                    <span class="btn btn-large btn btn-default">Revision</span>
                    <% end %>
                    <% if order.marking=="dispute" %>
                    <span class="btn btn-large btn btn-default">Dispute</span>
                    <% end %>
                </td>
                <td><span class="badge badge-default"><%= link_to "#{order.messages.count(:recipient)}", order %>
        </span></td>
            </tr>

        </tbody>

    </table>

app/views/orders/_unfollow.html.erb
<%= form_for(@order, html: { method: :mark }) do |f| %>
<span><%= f.hidden_field :marking, :value => 'complete' %></span>
<%= f.submit "Mark as Complete", class: "btn btn-large" %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= stylesheet_link_tag  "orders", media: "all" %>
<p id="notice"><%= notice %></p>
<%@orders.each do |order| %>
<table class="table table-striped">

        <thead>

            <tr>

                <th>Project Description</th>

                <th>Order ID</th>

                <th>Time remaining</th>

                <th>Order Status</th>
                <th>Messages</th>

            </tr>

        </thead>

        <tbody>

            <tr>

                <td rowspan="3"><%= link_to "#{order.instructions}", order%></td>

                <td>#<%=order.id%></td>

                <td><%=order.urgency%></td>
                <td> <% if order.marking=="complete"%>
                    <span class="btn btn-small btn btn-default">Complete</span>
                    <% end %>
                    <% if order.marking=="revision" %>
                    <span class="btn btn-large btn btn-default">Revision</span>
                    <% end %>
                    <% if order.marking=="dispute" %>
                    <span class="btn btn-large btn btn-default">Dispute</span>
                    <% end %>
                </td>
                <td> <%= link_to "#{order.messages.count(:recipient)}", order %></span></span></td>
            </tr>
        </tbody>

    </table>
<% end%>
    

app/views/orders/new.html.erb
<%= stylesheet_link_tag "customers", media: "all" %>
	<div id="elixirs">
		<% unless signed_in?%>
<div id="login">
	<%= render :file => 'sessions/new' %>
</div>
  <% end %>
<div id="features">
	<h4><span class="btn btn-large btn btn-info">Topics Covered</span></h4>
		<ul>
   <li>Art and Design</li>
    <li>Business and Economics</li>
    <li>Communication and Media</li>
    <li>Education</li>
    <li>Health and Medicine</li>
    <li>History</li>
    <li>IT</li>
    <li>Law</li>
    <li>Literature and Languages</li>
    <li>Mathematics</li>
    <li>Natural Sciences</li>
    <li>Political Sciences</li>
    <li>Social Sciences</li>
    <li>Technology and Engineering</li>
    <li>...and Others!</li>
</ul>
</div>
<p></p>
<div id="features">
<h4><span class="btn btn-large btn btn-info">Service Features</span></h4>
		<ul>

   <li>FREE amendments</li>
    <li>FREE bibliography page</li>
    <li>FREE title page</li>
    <li>FREE Plagiarism report</li>
    <li>FREE Formatting</li>
    <li>100% original papers</li>
    <li>275 words per page</li>
    <li>Any citation style</li>
    <li>Guaranteed Privacy</li>
    <li> 24/7 customer support</li>
    <li>...and Others!</li>
</ul>
</div>

<div class="payments">
</div>
</div>

<div id="customer">
<% if notice %>
<p id="notice"><%=notice%></p>
<%end%>
<div id="customer2">
<%= render 'form' %>
</div>
</div>

app/views/orders/show.html.erb
<%= stylesheet_link_tag  "orders", media: "all" %>

<div id="show2">
<p id="notice"> <%=notice %></p>


    <table class="table table-striped">

        <thead>

            <tr>
            	<th>Paper ID</th>

                <th>Order Topic</th>

                <th>Deadline</th>

                <th>Order Type</th>

                <th>Style</th>

                <th>Language</th>

                <th>No of Pages</th>

                <th>No of Sources</th>

                <th>Instructions</th>

                <th>Total Cost</th>

            </tr>

        </thead>

        <tbody>

            <tr>
            	<td><%=@order.id%></td>

                <td><%= @order.topic %></td>

                <td><%= @order.created_at + @order.deadline.hours%></td>

                <td><%=@order.documenttype%></td>

                <td><%= @order.citation %></td>

                <td><%= @order.language %></td>

                <td><%=@order.pages%></td>

                <td><%=@order.references%></td>

                <td><%= @order.instructions %> </td>

                <td>$<%=@total_price%></td>
            </tr>
        </tbody>

        </table>
        <table class="table">
        	<tbody>
            <tr>
            	<td>
            		<%if @order.payments.empty? %>
            		<%=link_to image_tag("Paypal.png", :alt=>"Buy With PayPal"), @order.paypal_url(orders_url, notification_orders_url)%>
            		<%else%>
            		<b class="btn btn-large btn btn-info"> Processing <b>
            		<% end %>
            	</td>
            	<td id="uploads">

            		<%= render :file => 'uploadfiles/new' %>
            		<% if @order.uploadfiles%>
            		<% @order.uploadfiles.each do |uploadfile| %>
            			<span><%= uploadfile.name %></span>:
            			<span><%= link_to "Download file", uploadfile.attachment_url %></span></br>
            			<% end %>
            		<% end %>
            	</td>
            	<td>
            		<% if current_user.admin %>
            		<li class="btn btn-small btn-default"><%= link_to "Mark as Complete", order_path(@order, :order=>{:marking=>"complete"}), :method=>:put, :confirmation=>"Are you Sure"%></li>
            		<% end%>
            	</td>
            </tr>
            <tr class="active">
            	<td id="contactus">
            		<em> Your order will be done as soon as you pay </em>
            	</td>
            	<td id="message4">
            		<%=link_to "Contact Support", new_order_message_path(@order, :format=>:js),
            	:remote=>true, :id=>'new_message_link', :class=>"btn btn-small btn-danger"  %>
            </td>
            <td>
            	<%=link_to "Messages", order_messages_path(@order, :format=>:js),
            	:remote=>true, :id=>'read_message_link' %>|<span class="badge badge-important">
            	<%=@order.messages.count(:sender) %></span>
            	<p id="features"> </p>
            </td>

        </tr>
    </tbody>

    </table>