config/routes.rb
Essaypros::Application.routes.draw do

  resources :customers
  resources :articles

  resources :orders do
    resources :uploadfiles
    resources :messages
    collection do
      post 'notification'
    end
  end
  resources :sessions, :only=>[:new, :create, :destroy]
  match '/signup', :to=>"customers#new"
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy', :via=>:delete
  match '/order_now', :to=>"orders#new"
  match '/pricing', :to=>'pages#pricing'
  match '/order_now', :to=>"orders#new"
  resources :password_resets

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
    &copy; Theacademicwriters <%=(Time.now.year) %> <br> All trademarks and registered trademarks appearing on this site are the property of their respective owners.
</footer>

app/views/layouts/_header.html.erb
<div class="account">
<% if signed_in? %>
<h1>Account/Orders</h1>
<ul>
    <li>Welcome: <%=current_user.firstname%></li>
    <li><%= link_to "My Orders", current_user%></li>
    <li><%= link_to "Profile", edit_customer_path(current_user)%></li>
    <li><%= link_to "Sign out", signout_path, :method=> "delete" %></li>
                <%# else %>
            <%#= link_to "Sign in", signin_path %>
    </ul>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Essaypros</title>
  <%= stylesheet_link_tag "sessions", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="top">
		<div id="logo">
<h1>AcademicWriters.com </h1>
</div>

</header>
<nav>
<ul id="navs">
	<% if signed_in?%>
    <li class="btn btn-large btn btn-default"><em><%= link_to "Profile", edit_customer_path(current_user)%></em></li>
    <% if current_user.admin %>
    <li class="btn btn-large btn btn-default"><em><%= link_to "Orders", orders_url %></em></li>
    <li class="btn btn-large btn btn-default"><em><%= link_to "Users", customers_url%></em></li>
    <li class="btn btn-large btn btn-default"><em><%= link_to "Blog",  articles_path %></em></li>
    <% else %>
    <li class="btn btn-large btn btn-default"><em><%= link_to "My Orders", current_user%></em></li>
    <% end %>
    <li class="btn btn-large btn btn-default"><em><%= link_to 'processing_orders', '#'%></em></li>
    <li class="btn btn-large btn btn-default"><%= link_to 'complete_orders', '#'%>|
      <% @complete=Order.where(:marking=>"complete") %>
        <span class="badge badge-important">
        <%= @complete.count %>
        </span>
    </li>
    
    <li class="btn btn-large btn btn-default"><%= link_to 'revisions', '#'%>|
      <% @revision=Order.where(:marking=>"revision") %>
        <span class="badge badge-important">
        <%= @revision.count %>
        </span>
    </li>
    <li class="btn btn-large btn btn-default"><%= link_to 'disputed', '#'%>|
      <% @disputed=Order.where(:marking=>"dispute") %>
        <span class="badge badge-important">
        <%= @disputed.count %>
        </span>

    </li>
    <li class="btn btn-large btn btn-default"><em><%= link_to "Sign out", signout_path, :method=> "delete" %></em></li>
    <%else%>
              <li class="btn btn-large btn btn-default"><em><%=link_to "Home", root_path %></em></li>
              <li class="btn btn-large btn btn-warning"><big><%=link_to "Order Now", order_now_path %><big></li>
              <li class="btn btn-large btn btn-default"><em><%=link_to "Pricing", pricing_path %></em></li>
              <li class="btn btn-large btn btn-default"><em><%= link_to "Blog",  articles_path %></em></li>
              <li class="btn btn-large btn btn-default"><em><a href="st.html">About Us</a></em></li>
              <% end %>
</ul>
</nav>
  <%= yield %>
</body>

</html>